### PR TITLE
Add argument to weave function to disable unicode escape

### PR DESCRIPTION
**Pull request by sebastianpech**
uc2tex isn't working very well:
- The minority of mappings in latex_symbols actually maps to valid latex commands
- Some of the commands are not valid in math mode

I tried to find a better solution to that (See JuliaDocs/Highlights.jl#30) but thats not very simple and one needs to add a lot of packages to LaTeX.
In my opinion the best way is to use XeLaTeX and try to find a font that is actually able of rendering the unicode chars.

So I added this switch that disables uc2tex (not the default).

### CODE REVIEW

**Comment by sebastianpech** [comment]
This relies on JuliaDocs/Highlights.jl#30 being merged.

**Comment by pfitzseb** [comment]
What do you think about renaming `escape_unicode` to `latex_unicode` or something similar (to indicate that it's only relevant for latex-y outputs)? Probably also a good idea to mention that in the docstring.

**Comment by sebastianpech** [comment]
Good point, will do that. Maybe `latex_keep_unicode` and switch true and false.

As the new Highlights.jl seems to be picked up the escape stuff now works. However, the tests now fail with
`/home/travis/.julia/packages/GR/ZI5OE/src/../deps/gr/bin/gksqt: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory`. Any ideas on that?

**Comment by sebastianpech** [comment]
Oh wait, maybe its unrelated to that. I didn't see the failed test at the end.

**Comment by pfitzseb** [comment]
Yeah, seems like [this](https://travis-ci.org/JunoLab/Weave.jl/jobs/598120341#L730) is the only relevant error.

**Comment by sebastianpech** [comment]
Oh ok. It's the new escaping I added to Highlights. Now `"` is placed as `\"{}` to allow usage of the babel package

**Comment by sebastianpech** [comment]
Hmm, so I have another PR (JuliaDocs/Highlights.jl#38) pending that again changes the escaping behavior. Should I mark the test as broken or skip it and when the Highlights PR is merged, update it?

**Comment by pfitzseb** [comment]
That PR doesn't seem to make any changes to the `"` printing, so I think it's fine to just change the expected output here.

**Comment by sebastianpech** [comment]
You're right, but it changes the escaping of all whitespace chars so the code needs to be fixed anyways. But I will fix it here, so the tests work on master until the PR gets merged.

**Comment by sebastianpech** [comment]
After renaming the kw argument it's name didn't really match the implementation I had before. That's why I moved the latex unicode escaping stuff to the `formatdict` of latex based formats to pass the option down to the chunk format functions. I think that's a cleaner method. The key is overwritten with the value of the kw argument in `run`.

**Comment by sebastianpech** [comment]
Bump @pfitzseb

**Comment by pfitzseb** [comment]
Oops, sorry for the delay.

**Pull request merged**
