### PR TITLE
Make assets `PackageCompiler`-friendly

### PR DESCRIPTION
**Pull request by MichaelHatherly**
As discussed briefly on slack yesterday. A possible solution to relocatablilty issues with the hardcoded paths.

Embeds the asset folder contents into the precompiled files. When the original folder isn't available (due to relocation) creates a scratchspace containing the original folder contents and uses that instead. Might be worth breaking this out into a small package if we actually go with this approach.

The other option is to just go with full artifacts for now until https://github.com/JuliaLang/julia/issues/38696 gives a more lightweight solution. It's a bit of a hassle to update them when things change though, hence why I've given this a try to see how it feels.

### CODE REVIEW

**Comment by pfitzseb** [comment]
LGTM, but I do feel like this should go into a separate package.

**Comment by MichaelHatherly** [comment]
JuliaPackaging org might be a decent home for it then, do you have access to that one @pfitzseb? (In the meantime I'll push to my personal account.)

**Comment by pfitzseb** [comment]
I don't. Maybe we can get @staticfloat to handle the transfer if you give him access?

**Comment by staticfloat** [comment]
Yeah, I can do that.

**Comment by MichaelHatherly** [comment]
Package is at https://github.com/MichaelHatherly/RelocatableFolders.jl and registration PR  is https://github.com/JuliaRegistries/General/pull/38805. I'll give @staticfloat access to that repo, and we'll just need to update the registration PR to point to the right place as well.

**Comment by staticfloat** [comment]
I accepted the invitation, but I can't see the `Settings` tab, so I don't think I have high enough privileges.

**Comment by MichaelHatherly** [comment]
Looks like there can only be a single "owner" of a personal repo. I've tried instead to transfer ownership to JuliaPacking but that yielded a "You don’t have the permission to create public repositories on JuliaPackaging" error.

**Comment by staticfloat** [comment]
Try transferring it to me, and I'll transfer it to JuliaPackaging

**Comment by staticfloat** [comment]
done

**Comment by MichaelHatherly** [comment]
Bump.

**Pull request merged**
